--- # playbook to understand handlers
- name: understand handlers using nginx web server
  hosts: default
  connection: ssh
  vars:
    pkgname: nginx
  tasks: 
    - name: task to install nginx
      action: apt name='{{pkgname}}' state=present
      notify:
       - start nginx
  handlers:
    - name: handler to start nginx
      service:
        name: nginx
        state: started

#output when i run this file in terminal
#############
Last login: Thu Apr 20 15:02:41 on ttys000
rvvssaibabuthotakura@Rsr ~ % cd Desktop/ansible-Main
rvvssaibabuthotakura@Rsr ansible-Main % ls
ansible-remote.pem	hosts			tomcat-setup.yml
ansible.cfg		inventory.ini		vars.yml
handlers.yml		roles
rvvssaibabuthotakura@Rsr ansible-Main % ansible-playbook handlers.yml -i hosts
ERROR! 'variables' is not a valid attribute for a Play

The error appears to be in '/Users/rvvssaibabuthotakura/Desktop/ansible-Main/handlers.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

--- # playbook to understand handlers
- name: understand handlers using nginx web server
  ^ here
rvvssaibabuthotakura@Rsr ansible-Main % ansible-playbook handlers.yml -i hosts

PLAY [understand handlers using nginx web server] ******************************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [task to install nginx] ***************************************************
ok: [default]

PLAY RECAP *********************************************************************
default                    : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

rvvssaibabuthotakura@Rsr ansible-Main % 
########